### ISSUE TITLE
A Couple of Feature Requests

### ISSUE THREAD

**Issue by GrowthPilgrim** [recklyss/markdown-timeline#1]
Hey, thx for the neat plugin. Just tried it out and my first use case was creating a timeline of my yearly themes. Two features came to mind:
- Support for years or months only (in my case I don't need the day, or month)
- Support for Wikilinks (it would be nice if I could jump to each note of my themes)

<img src="https://github.com/user-attachments/assets/c2caec57-d724-452a-9d6c-74c8b6f981fd" width="250">

**Comment by recklyss** [comment]
Thanks for your feature request, I've updated the plugin and please upgrade to `0.0.2` to check the new feature.
